openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: rsuperiodelacruz@my.bcit.ca
paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets processed statistics for goal and boost events
      responses:
        '200':
          description: Successfully returned event statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    AccountStats:
      required:
        - num_goal_events
        - max_goal_speed
        - num_boost_events
        - total_boost_pickups
        - avg_boost_per_event
      type: object
      properties:
        num_goal_events:
          type: integer
          example: 500
        max_goal_speed:
          type: number
          format: float
          example: 120.5
        num_boost_events:
          type: integer
          example: 1000
        total_boost_pickups:
          type: integer
          example: 250
        avg_boost_per_event:
          type: number
          format: float
          example: 50.0
